[package]
name          = "lapin-futures-openssl"
version       = "0.10.1" # remember to update html_root_url
edition       = "2018"
authors       = ["Marc-Antoine Perennou <%arc-Antoine@Perennou.com>"]
description   = "Integration of openssl with lapin-futures"
repository    = "https://github.com/sozu-proxy/lapin-futures-tls"
documentation = "https://docs.rs/lapin-futures-openssl"
keywords      = ["amqp","rabbitmq","futures","tokio","tls"]
categories    = ["api-bindings","network-programming"]
license       = "BSD-2-Clause"

[lib]
name = "lapin_futures_openssl"

[features]
default      = ["dns-over-tls"]
dns-over-tls = ["lapin-futures-tls-internal/dns-over-openssl"]

[dependencies]
futures       = "^0.1"
openssl       = "^0.10"
tokio-openssl = "^0.3"

[dependencies.lapin-futures-tls-internal]
version = "^0.7.1"
path    = "../internal"

[dev-dependencies]
env_logger = "^0.6"
failure    = "^0.1"
tokio      = "^0.1.6"

[badges]
travis-ci = { repository = "sozu-proxy/lapin-futures-tls" }
appveyor  = { repository = "Keruspe/lapin-futures-tls" }
